language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t gpsolinski/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true gpsolinski/react-test yarn test

after_success:
    - docker build -t gpsolinski/multi-client ./client
    - docker build -t gpsolinski/multi-nginx ./nginx
    - docker build -t gpsolinski/multi-server ./server
    - docker build -t gpsolinski/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to Docker Hub
    - docker push gpsolinski/multi-client
    - docker push gpsolinski/multi-nginx
    - docker push gpsolinski/multi-server
    - docker push gpsolinski/multi-worker