apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: filoflamki-net-tls
spec:
  secretName: filoflamki-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: filoflamki.net
  # List of all the different domain that should be associated with the certificate
  dnsNames:
    - filoflamki.net
    - www.filoflamki.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        # List of the domains that the verification process is going to access to verify them
        domains:
          - filoflamki.net
          - www.filoflamki.net