apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:  # additional configuration options, specifying higher-level configuration around the Ingress object that gets created
    kubernetes.io/ingress.class: nginx                # create an ingress controller based on the nginx project
    nginx.ingress.kubernetes.io/rewrite-target: /$1   # configuring the acual controller - rewrite strategy
    cert-manager.io/issuer: "letsencrypt-prod"        # let our ingress service know we are using a certificate
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts: 
        - filoflamki.net
        - www.filoflamki.net
      secretName: filoflamki-net
  rules:
    - host: filoflamki.net
      http:
        paths:
          - path: /?(.*)
            backend: 
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
    - host: www.filoflamki.net
      http:
        paths:
          - path: /?(.*)
            backend: 
              serviceName: client-cluster-ip-service
              servicePort: 3000
          - path: /api/?(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000