apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server url
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: 'gpsolinski@gmail.com'
    # This is not our secret key, only a secret key that LetsEncrypt sends us in the verification process (ACME account secret key)
    privateSecretKeyRef:
      name: letsencrypt-prod
    solvers:
        # We want to go through the http way of obtaining the certificate
      - http01:
        ingress:
          class: nginx