apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'gpsolinski@gmail.com'
    privateSecretKeyRef:
      # This is not our secret key, only a secret key that LetsEncrypt sends us in the verification process
      name: letsencrypt-prod
    # We want to go through the http way of obtaining the certificate
    http01: {}